---
title: "everything_else"
author: "Stephanie Bland"
date: '2017-11-25'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
The role of fish life-histories in allometrically scaled foodweb dynamics (worktitle)

## Introduction

The complexity-stability debate has been a long standing point of discussion in ecology (May  Model ecosystems, p. 37). On one hand, diverse communities are both abundant and apparently extremely stable in nature, as one would find in coral reefs and tropical rainforests. This apparent trend has led some early ecologists (Elton, 1958, p. 145-150;  Hutchinson 1959, p. 155; Pimentel, 1961) to conclude that complex ecosystems are inherently more stable than simpler ones. However, the opposite was demonstrated through the theory of complex multispecies dynamics: May (19XX) showed with a simple mathematical model of a random interaction network that complexity, in fact, destabilizes ecosystems. Much of the ensuing work has been trying to resolve the discrepancy between theory and empirical observations (May  Model ecosystems, p. 39).

The answer to the enigma of stability lies not so much in complexity, but in structure. May's initial mathematical model made the assumption that species interactions are randomly distributed throughout the community. In reality, ecosystems are fairly structured and structural properties, such as allometric scaling, interaction strength, network structure, and functional responses, have been demonstrated to stabilize complex food webs (refs: Brose et al. 2006, Otto et al. 2007). [Brose et al 2006 has references for all the structural properties in the first paragraph]

The study on ecological networks has recently achieved major breakthroughs by recognizing that the ecological functionality of species can be largely attributed to their body sizes (Brose et al. 2006, Otto et al. 2007). Specifically, large predator-prey body size ration has been found the key attribute to stabilize dynamics of complex food webs (Brose et al 2006 eco letters). Through scaling by body size, the so-called allometrically scaled network (ATN) models have proven successful in explaining the stability, structure and functioning of ecosystems (Brose et al. 2006, refs: Dunne, Martinez?). Apart from model-based investigations on the role of body size in food web dynamics, the theory has been further verified by Boit et al. (2012), who showed that, when scaled by body size alone, an ATN approach can explain about one third of variation in the seasonal dynamics of the Lake Constance plankton community. (also look at references (Yodzis & Innes 1992; Jonsson & Ebenman 1998; Emmerson & Raffaelli 2004)

Within the context food web dynamics models in general and ATN models in particular, similar species are traditionally clumped together in one functional group, such that scaling by body size as done with respect to individual body size across its lifespan. This approach stemmed from the need to develop simple models to address generic questions, for example, about the coexistence of species (ref). However, for some species an individual's body size can change by several orders of magnitude across its lifetime. As there are strong correlations between body size and key functional traits, such as metabolic rate (ref), a species' ecological functionality is likely to change substantially from juvenile to adult life-history stages. Thus, incorporation of the life-history structure of species that experience substantial changes in their body size across their lifespan is likely to increase structural realism of food webs and yield more biologically realistic prediction about their dynamics.

Fish are an ideal study species because of their indeterminate growth, which causes them to shift through several ecological niches as they grow. Their body size, diet, exposure to predation, and general ecological functionality changes tremendously from larvae to adult stages, rising them from the bottom of the food chain to become apex predators (Wooton). For example, Atlantic cod (Gadus morhua) larvae grows from few millimeter length planktivores and X g weight up to about one meter and Y kg carnivores within 5-6 years (ref). Another aspect that makes fishes and aquatic food webs particularly interesting systems to study the role of life-history structures in food web dynamics is that fact that contemporary life-history trends towards smaller body sizes and earlier maturity have been documented in many fish species across the world (Audzijonyte et al. Devine et al.). Understanding the impacts that such life-history changes can have to the interacting species and the entire ecosystem warrants for knowledge about the role of fish life-histories in food web dynamics. In the present study we expand the ATN modelling approach with life-history structure for fishes and explore the role of the life histories across a broad range to alternative scenarios for aquatic food webs. To this end, we utilize the generic allometrically scaled niche model (Martinez) adapted to aquatic food webs (Tonin et al.) to randomly generate scenarios for food webs, within which we introduce life-history structure to fishes and split the species level diets among the life-history stages. Through systematic simulations we disentangle the relative impacts of the following components involved in the added life-history structure: i) extending the food web to include new nodes, ii) life-history dynamics moving biomass from previous life-history stage to the next and into new larvae through reproduction, and iii) the role of different fish life-history types, characterized through traits such as species growth speed and body size, timing of maturity, and diet. These analyses will provide broadly generalizable insights into the ways in which fish life-histories affect their food webs.   




## Simulation design and analyses

We investigated the model through systematic simulations for two major objectives: Firstly, in order to detect how inclusion of fish life-history structure affects the food web, its structure, dynamics, and stability. Secondly, to investigate how alternative fish life-history strategies are associate with the properties of the food webs. The addition of the  life-history structure for fisheschanges multiple features of the food web. Introduction of life-history stages adds new nodes and feedings links to the web and life-history dynamics (growth from one life-history stage to the next) alters the ways in which biomass is transfers within the food web. To tease apart the relative roles of these components involved with the life-history structures,  we run 3 sets of simulations (hereafter denoted as "experiments"):

1.	Original Web: Each species, including fish, is described through one single node in the food web. 
2.	Life History stages: We split the fish species into life-history stages, but we do not  link them together with leslie matrices. The new fish life stages are independent of each other and (biomass does not growth from one stage to author) and,  thus, they can be considered as new species. While this experiment is not biologically realistic, it is crucial for disentangling the effects of adding new nodes to the food web from the effect of life-history dynamics. 
3.	Life-history dynamics: Here we link the life-history stages together with a Leslie matrix.  

To compare these three experiments, we use the same initial conditions for all of them and run 500 simulations in each experiment for a paired comparison.  In each simulation, the food web is allowed to stabilize for 100 years, after which the food web is either accepted or rejected based on the rules detailed below. The dynamics of the food webs are then investigated across another 100 year period. Each year consists of 100 simulation time steps, representing a 100 day growth season. 
Because our objective is to study the impact of fish life-history stages, we choose amongst the stabilized food webs only those that contain at least one fish species or at least one fish life-history stage (in experiment 2). 
We will conduct a preliminary analysis on the probability of extinction in each experiment. For this analysis we will only discard webs where all fish go extinct in every experiment. The reamining analyses will have a more stringent constraint; at least one fish species must persist in every experiment for the web to be included.


## Results

The original web has the most amount of extinctions because if the only life stage goes extinct, then the entire species goes extinct. When you add in more life stages, the extinction rate decreases. When these life stages are linked with leslie matrices, the chance of any single fish species surviving increases because you only need one really strong life stage to maintain the survival of a species. However, the chance of all the species surviving decreases because it's more likely for a single life stage from each species to surive than for all the fish to have exactly the right life stages to persist.


## Conclusion

Quote Lord Rob May when talking about how only a few of my randomly generated ecosystems are actually stable: "Natural ecosystems, whether structurally complex or simple, are the product of  a long history of coevolution of their constituent plants and animals. It is at least plausible that such intricate evolutionary processes have, in effect, sought out those relatively tiny and mathematically atypical regions of parameter space which endow the system with long-term stability." (May, Model ecosystems, p. 173)





